CREATE TABLE STUDENTS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    SURNAME TEXT NOT NULL
);

CREATE TABLE ADMINS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME TEXT NOT NULL,
	PASSWORD TEXT NOT NULL,
	NAME TEXT NOT NULL,
    SURNAME TEXT NOT NULL
);

CREATE TABLE ANSWERS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
	ASSIGNMENTID INTEGER NOT NULL,
	QUESTIONID INTEGER NOT NULL,
    CODE TEXT NOT NULL,
	CONSTRAINT UC_ANSWERS UNIQUE (ASSIGNMENTID,QUESTIONID)
);

CREATE TABLE ASSIGNMENTS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    STUDENTID INTEGER NOT NULL,
	EXAMCODE TEXT NOT NULL,
	ISCOMPLETED INTEGER NOT NULL DEFAULT 0,
	SCORE INTEGER NOT NULL DEFAULT 0,
	COMPLETEDDATE TEXT DEFAULT NULL,
	DEADLINE TEXT NOT NULL,
	CONSTRAINT UC_ASSIGNMENTS UNIQUE (STUDENTID,EXAMCODE)
);